#!/bin/sh

APPDIR=$(dirname "$(readlink -f "$0")")
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"

export CHROME_USER_DATA_DIR="${HOME}/.config/chromium65"

exec "$APPDIR/usr/bin/chrome" "$@"
